import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useContext, useEffect, useState } from 'react';

// Translation data
const translations = {
  en: {
    // Textbook Component
    class10Textbooks: "Class 10 Textbooks",
    chooseMediumAndSubject: "Choose your medium and subject",
    englishMedium: "English Medium",
    nepaliMedium: "Nepali Medium",
    subjects: "subjects",
    english: "English",
    mathematics: "Mathematics",
    science: "Science",
    socialStudies: "Social Studies",
    computerScience: "Computer Science",
    optionalMath: "Optional Mathematics",
    
    // Authentication
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    joinEduNepal: "Join elearn Nep today",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    error: "Error",
    // Drawer descriptions
    drawerDescHome: "Navigate to the main dashboard",
    drawerDescProfile: "View your profile information",
    drawerDescSettings: "Manage application preferences",
    drawerDescLanguage: "Change the application language",
    drawerDescDownloads: "View your downloaded content",
    drawerDescTheme: "Switch light/dark mode",
    drawerDescHelpSupport: "Find answers or contact support",
    drawerDescTerms: "Read terms and policies",
    drawerDescContactUs: "Reach out for queries",
    // Settings (index)
    settingsSearchPlaceholder: "Search settings...",
    settingsSearchResults: "Search Results",
    settingsNoMatches: "No matches found",
    settingsAdminControls: "Admin Controls",
    settingsAccountSecurity: "Account Security",
    settingsPrivacyData: "Privacy & Data",
    settingsNotifications: "Notifications",
    settingsPreferences: "Preferences",
    settingsHelpSupport: "Help & Support",
    settingsAbout: "About",
    settingsAccountActions: "Account Actions",
    adminDashboard: "Admin Dashboard",
    adminDashboardDesc: "Manage users, content, and system",
    changePassword: "Change Password",
    changePasswordDesc: "Update your account security settings",
    updateEmail: "Update Email Address",
    updateEmailDesc: "Change your email",
    deleteAccount: "Delete Account",
    deleteAccountDesc: "Permanently delete your account",
    privacyDashboard: "Privacy Dashboard",
    notificationSettings: "Notification Settings",
    notificationSettingsDesc: "Manage all notification preferences",
    choosePreferredLanguage: "Choose your preferred language",
    languageChangeAppliedImmediately: "Language changes will be applied immediately across the entire app.",
    contentRegion: "Content Region",
    contentRegionValueNepal: "Nepal",
    themeSettings: "Theme Settings",
    themeSettingsDesc: "Light, Dark, or Auto",
    userGuides: "User Guides",
    applicationVersion: "Application Version",
    roleAdministrator: "Administrator",
    roleStudent: "Student",
    userFallback: "User",
    // Admin
    admin: "Admin",
    adminNotificationCenter: "Notification Center",
    adminNotificationCenterDesc: "View history and manage notifications",
    adminLogin: "Admin Login",
    userLogin: "User Login",
    demoCredentials: "Demo Credentials",
    email: "Email",
    password: "Password",
    username: "Username",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    alreadyHaveAccount: "Already have an account? Login",
    
    // Admin Dashboard
    adminAccessDenied: "Access denied. Admins only.",
    adminDashboardTitle: "Admin Dashboard",
    adminWelcomeBack: "Welcome back,",
    systemOverview: "System Overview",
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    onlineUsers: "Online Users",
    contentItems: "Content Items",
    booksNotesPapers: "Books, notes, papers",
    systemHealth: "System Health",
    last24Hours: "Last 24 hours",
    live: "Live",
    userManagement: "User Management",
    userManagementDesc: "Manage student accounts and permissions",
    contentManagement: "Content Management",
    contentManagementDesc: "Upload and organize educational materials",
    systemAnalytics: "System Analytics",
    systemAnalyticsDesc: "View detailed usage statistics and reports",
    notificationCenter: "Notification Center",
    notificationCenterDesc: "Send announcements to all users",
    systemSettings: "System Settings",
    systemSettingsDesc: "Configure app-wide settings and preferences",
    backupSecurity: "Backup & Security",
    backupSecurityDesc: "Manage data backups and security settings",
    systemStatus: "System Status",
    serverStatus: "Server Status",
    database: "Database",
    connected: "Connected",
    disconnected: "Disconnected",
    storageUsed: "Storage Used",
    online: "Online",
    offline: "Offline",
    
    // Profile
    profile: "Profile",
    personalInformation: "Personal Information",
    accountDetails: "Account Details",
    emailAddress: "Email Address",
    accountRole: "Account Role",
    memberSince: "Member Since",
    location: "Location",
    editProfile: "Edit Profile",
    loadingProfile: "Loading Profile...",
    welcomeToEduNepal: "Welcome to elearn Nep",
    classes: "Classes",
    class: "Class",
    years: "Years",
    active: "Active",
    // Class subtitles
    classSubtitle1: "Foundational studies for young learners",
    classSubtitle2: "With engaging lessons and activities",
    classSubtitle3: "Intermediate learning with focus",
    classSubtitle4: "Advanced topics and applications",
    classSubtitle5: "Comprehensive curriculum for all",
    classSubtitle6: "Deeper dives into science, math, and more",
    classSubtitle7: "Pre-secondary foundational content",
    classSubtitle8: "Secondary education basics",
    classSubtitle9: "Advanced secondary topics",
    classSubtitle10: "Preparation for SEE Examination",
    classSubtitle11: "Higher secondary foundation",
    classSubtitle12: "Bridge to university education",
    
    // Navigation
    home: "Home",
    settings: "Settings",
    language: "Language",
    downloads: "Downloads",
    theme: "Theme",
    helpSupport: "Help & Support",
    helpSupportSubtitle: "Find answers, contact us, and explore helpful resources",
    termsConditions: "Terms & Conditions",
    contactUs: "Contact Us",
    contactSubtitle: "Get in touch with our support team",
    aboutApp: "About App",
    privacyPolicy: "Privacy Policy",
    userGuides: "User Guides",
    accountSecurity: "Account Security",
    adminDashboard: "Admin Dashboard",
    systemNotifications: "System Notifications",
    systemLogs: "System Logs",
    developerTools: "Developer Tools",
    notificationSettings: "Notification Settings",
    languageRegion: "Language & Region",
    regionSettings: "Region Settings",
    privacySettings: "Privacy Settings",
    updatePassword: "Update Password",
    updateEmail: "Update Email",
    deleteAccount: "Delete Account",
    visitWebsite: "Visit Website",
    reportBug: "Report a Bug",
    phoneSupport: "Phone Support",
    officeAddress: "Office Address",
    explore: "Explore",
    contactFooter: "We're here to help! Reach out anytime for support, feedback, or questions about elearn Nep.",
    
    // General
    general: "General",
    supportAccount: "Support & Account",
    eduNepal: "elearn Nep",
    optional: "Optional",
    required: "Required Information",
    optionalInformation: "Optional Information",
    comingSoon: "Coming Soon",
    loading: "Loading...",
    quickActions: "Quick Actions",
    faqs: "FAQs",
    resources: "Resources",
    emailSupport: "Email Support",
    callUs: "Call Us",
    contact: "Contact",
    shareApp: "Share App",
    shareAppMessage: "Check out elearn Nep! https://www.elearn.com",
    unableToShareNow: "Unable to share right now.",
    faqResetPasswordQ: "How do I reset my password?",
    faqResetPasswordA: "Go to Settings > Account Security > Change Password to reset your password.",
    faqContactSupportQ: "How can I contact support?",
    faqContactSupportA: "Use Contact Us to email elearnnep@16gmail.com or call +977-9864158297.",
    faqPrivacyQ: "Where can I read the Privacy Policy?",
    faqPrivacyA: "Go to Settings > About > Privacy Policy or tap the Privacy Policy link below.",
    faqDeleteAccountQ: "How do I delete my account?",
    faqDeleteAccountA: "Go to Settings > Account Security > Delete Account and follow the steps.",
    // Generic errors
    error: "Error",
    unableToLoadDownloads: "Unable to load downloads",
    failedToShareFile: "Failed to share file",
    failedToDeleteFile: "Failed to delete file",
    failedToDeleteSomeFiles: "Failed to delete some files",
    failedToClearAll: "Failed to clear all files",
    
    // Class Screen
    class: "Class",
    searchBooksNotes: "Search for books, notes...",
    textbooks: "Textbooks",
    guidebooks: "Guidebooks",
    previousPapers: "Previous Papers",
    practiceQuestions: "Practice Questions",
    cdcApprovedBooks: "CDC-approved books in English & Nepali",
    chapterWiseNotes: "Chapter-wise notes, explanations, and exam",
    lastYearsExams: "Access last 3–5 years' Board/Final exam",
    expectedQuestions: "Expected questions for exams: short, long",
    recentActivity: "Recent Activity"
    ,
    // Notifications
    notifications: "Notifications",
    clearAll: "Clear All",
    noNotificationsYet: "No notifications yet",
    markAsRead: "Mark as Read",
    markAsUnread: "Mark as Unread",
    markAllAsRead: "Mark All as Read",
    markAllAsUnread: "Mark All as Unread"
    ,
    // Notification Settings screen
    notificationSettingsTitle: "Notification Settings",
    notificationSettingsSubtitle: "Manage how you receive notifications and updates",
    pushNotifications: "Push Notifications",
    pushNotificationsDesc: "Enable push notifications for real-time updates",
    studyReminders: "Study Reminders",
    studyRemindersDesc: "Get reminded about your study schedule and goals",
    newContentAvailable: "New Content Available",
    newContentAvailableDesc: "Notifications when new study materials are added",
    emailNotificationsSection: "Email Notifications",
    emailNotifications: "Email Notifications",
    emailNotificationsDesc: "Important updates and announcements via email",
    weeklyDigest: "Weekly Digest",
    weeklyDigestDesc: "Weekly summary of your progress and new content",
    marketingEmails: "Marketing Emails",
    marketingEmailsDesc: "Promotional offers and educational tips",
    systemSecuritySection: "System & Security",
    systemSecuritySectionDesc: "Important system and security notifications",
    smsAlerts: "SMS Alerts",
    smsAlertsDesc: "Critical security alerts via SMS",
    systemUpdates: "System Updates",
    systemUpdatesDesc: "App updates and maintenance notifications",
    infoChangeAnytime: "You can change these settings anytime. Some notifications may be required for security purposes.",
    saveNotificationSettings: "Save Notification Settings",
    saving: "Saving...",
    success: "Success",
    notifSettingsSaved: "Notification settings saved successfully!",
    failedToSaveSettings: "Failed to save settings. Please try again.",
    // Downloads toolbar/actions
    select: "Select",
    selectAll: "Select All",
    clear: "Clear",
    delete: "Delete",
    done: "Done",
    noDownloadsYet: "No downloads yet",
    downloadsAppearHere: "Your downloaded files will appear here.",
    cancel: "Cancel",
    clearAllConfirmTitle: "Clear All",
    clearAllConfirmMsg: "Delete all downloaded files?",
    deleteSelectedConfirmTitle: "Delete",
    deleteSelectedConfirmMsg: "Delete selected files?",
    selected: "selected",
    sharingNotAvailable: "Sharing not available on this device",
    // Privacy Policy
    privacyUpdated: "Last updated: January 2024",
    privacyIntro: "At EduNepal, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data.",
    privacyInfoWeCollectTitle: "Information We Collect",
    privacyInfoWeCollectContent: "We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.",
    privacyHowWeUseTitle: "How We Use Your Information",
    privacyHowWeUseContent: "We use the information we collect to provide, maintain, and improve our services, process transactions, and communicate with you.",
    privacySharingTitle: "Information Sharing",
    privacySharingContent: "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy.",
    privacySecurityTitle: "Data Security",
    privacySecurityContent: "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    privacyYourRightsTitle: "Your Rights",
    privacyYourRightsContent: "You have the right to access, update, or delete your personal information. You may also opt out of certain communications from us.",
    privacyChangesTitle: "Changes to This Policy",
    privacyChangesContent: "We may update this privacy policy from time to time. We will notify you of any changes by posting the new policy on this page.",
    privacyContactFooter: "If you have any questions about this Privacy Policy, please contact us at privacy@edunepal.com",
    privacyPolicySubtitle: "How we collect and use data",
    termsConditionsSubtitle: "Your rights and responsibilities",
    // Terms & Conditions
    termsUpdated: "Last updated: January 2024",
    termsIntro: "Please read these Terms and Conditions carefully before using elearn Nep. These terms govern your use of our educational platform and services.",
    termsAcceptanceTitle: "Acceptance of Terms",
    termsAcceptanceContent: "By accessing and using elearn Nep, you accept and agree to be bound by the terms and provision of this agreement.",
    termsUseLicenseTitle: "Use License",
    termsUseLicenseContent: "Permission is granted to temporarily access elearn Nep for personal, non-commercial transitory viewing only.",
    termsUserAccountTitle: "User Account",
    termsUserAccountContent: "You are responsible for safeguarding your account credentials and for all activities that occur under your account.",
    termsProhibitedUsesTitle: "Prohibited Uses",
    termsProhibitedUsesContent: "You may not use our service for any illegal or unauthorized purpose or to violate any laws in your jurisdiction.",
    termsContentTitle: "Content",
    termsContentContent: "Our service allows you to access educational content. You are responsible for your use of the content and must respect intellectual property rights.",
    termsPrivacyPolicyTitle: "Privacy Policy",
    termsPrivacyPolicyContent: "Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the service.",
    termsTerminationTitle: "Termination",
    termsTerminationContent: "We may terminate or suspend your account and access to the service immediately, without prior notice, for conduct that we believe violates these Terms.",
    termsChangesTitle: "Changes to Terms",
    termsChangesContent: "We reserve the right to modify these terms at any time. We will notify users of any material changes.",
    termsQuestionsFooter: "If you have any questions about these Terms and Conditions, please contact us at elearnnep@16gmail.com",
    termsPlaceholder: "Full text of Terms and Conditions goes here. This content describes how you may use the elearn Nep application and services, your responsibilities, and our policies."
  },
  
  ne: {
    // Textbook Component
    class10Textbooks: "कक्षा १० को पाठ्यपुस्तकहरू",
    chooseMediumAndSubject: "आफ्नो माध्यम र विषय चयन गर्नुहोस्",
    englishMedium: "अंग्रेजी माध्यम",
    nepaliMedium: "नेपाली माध्यम",
    subjects: "विषयहरू",
    english: "अंग्रेजी",
    mathematics: "गणित",
    science: "विज्ञान",
    socialStudies: "सामाजिक अध्ययन",
    computerScience: "कम्प्युटर विज्ञान",
    optionalMath: "वैकल्पिक गणित",
    
    // Authentication
    welcomeBack: "फिर्ता स्वागत छ",
    createAccount: "खाता सिर्जना गर्नुहोस्",
    joinEduNepal: "आज elearn Nep मा सामेल हुनुहोस्",
    login: "लगइन",
    signup: "साइन अप",
    logout: "लगआउट",
    error: "त्रुटि",
    // Drawer descriptions
    drawerDescHome: "मुख्य ड्यासबोर्डमा जानुहोस्",
    drawerDescProfile: "तपाईंको प्रोफाइल जानकारी हेर्नुहोस्",
    drawerDescSettings: "एपको प्राथमिकताहरू व्यवस्थापन गर्नुहोस्",
    drawerDescLanguage: "एपको भाषा परिवर्तन गर्नुहोस्",
    drawerDescDownloads: "तपाईंका डाउनलोड गरिएको सामग्री हेर्नुहोस्",
    drawerDescTheme: "हल्का/अँध्यारो मोड स्विच गर्नुहोस्",
    drawerDescHelpSupport: "उत्तरहरू खोज्नुहोस् वा समर्थन सम्पर्क गर्नुहोस्",
    drawerDescTerms: "नियम र नीतिहरू पढ्नुहोस्",
    drawerDescContactUs: "प्रश्नहरूका लागि सम्पर्क गर्नुहोस्",
    
    // Admin ड्यासबोर्ड
    adminAccessDenied: "प्रवेश अस्वीकार। केवल प्रशासकका लागि।",
    adminDashboardTitle: "प्रशासनिक ड्यासबोर्ड",
    adminWelcomeBack: "पुनः स्वागत,",
    systemOverview: "प्रणाली अवलोकन",
    totalUsers: "कुल प्रयोगकर्ता",
    activeUsers: "सक्रिय प्रयोगकर्ता",
    onlineUsers: "अनलाइन प्रयोगकर्ता",
    contentItems: "सामग्री वस्तुहरू",
    booksNotesPapers: "पुस्तकहरू, नोटहरू, पेपरहरू",
    systemHealth: "प्रणाली स्वास्थ्य",
    last24Hours: "पछिल्ला २४ घण्टा",
    live: "लाइभ",
    userManagement: "प्रयोगकर्ता व्यवस्थापन",
    userManagementDesc: "विद्यार्थी खाताहरू र अनुमति प्रबन्ध गर्नुहोस्",
    contentManagement: "सामग्री व्यवस्थापन",
    contentManagementDesc: "शैक्षिक सामग्री अपलोड र व्यवस्थित गर्नुहोस्",
    systemAnalytics: "प्रणाली विश्लेषण",
    systemAnalyticsDesc: "विस्तृत प्रयोग तथ्यांक र प्रतिवेदनहरू हेर्नुहोस्",
    notificationCenter: "सूचना केन्द्र",
    notificationCenterDesc: "सबै प्रयोगकर्तालाई सूचना पठाउनुहोस्",
    systemSettings: "प्रणाली सेटिङ्स",
    systemSettingsDesc: "एप-स्तरीय सेटिङ्स र प्राथमिकताहरू कन्फिगर गर्नुहोस्",
    backupSecurity: "ब्याकअप र सुरक्षा",
    backupSecurityDesc: "डाटा ब्याकअप र सुरक्षा सेटिङ्स प्रबन्ध गर्नुहोस्",
    systemStatus: "प्रणाली स्थिति",
    serverStatus: "सर्भर स्थिति",
    database: "डेटाबेस",
    connected: "जडित",
    disconnected: "विच्छेद",
    storageUsed: "प्रयोग गरिएको भण्डारण",
    online: "अनलाइन",
    offline: "अफलाइन",
    // Settings (index)
    settingsSearchPlaceholder: "सेटिङहरू खोज्नुहोस्...",
    settingsSearchResults: "खोज परिणाम",
    settingsNoMatches: "कुनै मिल्दो भेटिएन",
    settingsAdminControls: "प्रशासक नियन्त्रण",
    settingsAccountSecurity: "खाता सुरक्षा",
    settingsPrivacyData: "गोपनीयता र डाटा",
    settingsNotifications: "सूचनाहरू",
    settingsPreferences: "रूचिहरू",
    settingsHelpSupport: "मद्दत र समर्थन",
    settingsAbout: "बारेमा",
    settingsAccountActions: "खाता कार्यहरू",
    adminDashboard: "प्रशासक ड्यासबोर्ड",
    adminDashboardDesc: "प्रयोगकर्ता, सामग्री, र प्रणाली प्रबन्ध गर्नुहोस्",
    changePassword: "पासवर्ड परिवर्तन गर्नुहोस्",
    changePasswordDesc: "तपाईंको खाता सुरक्षा सेटिङहरू अद्यावधिक गर्नुहोस्",
    updateEmail: "इमेल ठेगाना अद्यावधिक गर्नुहोस्",
    updateEmailDesc: "तपाईंको इमेल परिवर्तन गर्नुहोस्",
    deleteAccount: "खाता मेटाउनुहोस्",
    deleteAccountDesc: "तपाईंको खाता स्थायी रूपमा मेटाउनुहोस्",
    privacyDashboard: "गोपनीयता ड्यासबोर्ड",
    notificationSettings: "सूचना सेटिङहरू",
    notificationSettingsDesc: "सबै सूचना प्राथमिकताहरू प्रबन्ध गर्नुहोस्",
    choosePreferredLanguage: "आफ्नो मनपर्ने भाषा छान्नुहोस्",
    languageChangeAppliedImmediately: "भाषा परिवर्तन तुरुन्तै सम्पूर्ण एपमा लागू हुनेछ।",
    contentRegion: "सामग्री क्षेत्र",
    contentRegionValueNepal: "नेपाल",
    themeSettings: "थिम सेटिङहरू",
    themeSettingsDesc: "हल्का, गाढा वा स्वत:",
    userGuides: "प्रयोगकर्ता मार्गदर्शिका",
    applicationVersion: "एप संस्करण",
    roleAdministrator: "प्रशासक",
    roleStudent: "विद्यार्थी",
    userFallback: "प्रयोगकर्ता",
    // Admin
    admin: "प्रशासक",
    adminNotificationCenter: "सूचना केन्द्र",
    adminNotificationCenterDesc: "इतिहास हेर्नुहोस् र सूचनाहरू व्यवस्थापन गर्नुहोस्",
    adminLogin: "प्रशासक लगइन",
    userLogin: "प्रयोगकर्ता लगइन",
    demoCredentials: "डेमो प्रमाणहरू",
    email: "इमेल",
    password: "पासवर्ड",
    username: "प्रयोगकर्ता नाम",
    fullName: "पूरा नाम",
    phoneNumber: "फोन नम्बर",
    rememberMe: "मलाई सम्झनुहोस्",
    forgotPassword: "पासवर्ड बिर्सनुभयो?",
    alreadyHaveAccount: "पहिले नै खाता छ? लगइन गर्नुहोस्",
    
    // Profile
    profile: "प्रोफाइल",
    personalInformation: "व्यक्तिगत जानकारी",
    accountDetails: "खाता विवरण",
    emailAddress: "इमेल ठेगाना",
    accountRole: "खाता भूमिका",
    memberSince: "सदस्य भएदेखि",
    location: "स्थान",
    editProfile: "प्रोफाइल सम्पादन गर्नुहोस्",
    loadingProfile: "प्रोफाइल लोड गर्दै...",
    welcomeToEduNepal: "elearn Nep मा स्वागत छ",
    classes: "कक्षाहरू",
    class: "कक्षा",
    years: "वर्षहरू",
    active: "सक्रिय",
    // Class subtitles
    classSubtitle1: "साना विद्यार्थीहरूका लागि आधारभूत अध्ययन",
    classSubtitle2: "रमाइलो पाठ र गतिविधिसहित",
    classSubtitle3: "मध्यम स्तरको एकाग्र अध्ययन",
    classSubtitle4: "उन्नत विषय र प्रयोग",
    classSubtitle5: "सबैका लागि समग्र पाठ्यक्रम",
    classSubtitle6: "विज्ञान, गणित आदि मा गहिरो अध्ययन",
    classSubtitle7: "पूर्व-माध्यमिक आधारभूत सामग्री",
    classSubtitle8: "माध्यमिक शिक्षाका आधारहरू",
    classSubtitle9: "उन्नत माध्यमिक विषयहरू",
    classSubtitle10: "SEE परीक्षाको तयारी",
    classSubtitle11: "उच्च माध्यमिकको आधार",
    classSubtitle12: "विश्वविद्यालयतर्फको सेतु",
    
    // Navigation
    home: "घर",
    settings: "सेटिङहरू",
    language: "भाषा",
    downloads: "डाउनलोडहरू",
    theme: "थिम",
    helpSupport: "मद्दत र समर्थन",
    helpSupportSubtitle: "उत्तरहरू खोज्नुहोस्, हामीलाई सम्पर्क गर्नुहोस्, र उपयोगी स्रोतहरू हेर्नुहोस्",
    termsConditions: "नियम र शर्तहरू",
    contactUs: "हामीलाई सम्पर्क गर्नुहोस्",
    contactSubtitle: "हाम्रो समर्थन टोलीसँग सम्पर्क गर्नुहोस्",
    aboutApp: "एप बारे",
    privacyPolicy: "गोपनीयता नीति",
    userGuides: "प्रयोगकर्ता मार्गदर्शन",
    accountSecurity: "खाता सुरक्षा",
    adminDashboard: "प्रशासक ड्यासबोर्ड",
    supportAccount: "समर्थन र खाता",
    eduNepal: "elearn Nep",
    optional: "वैकल्पिक",
    required: "आवश्यक जानकारी",
    optionalInformation: "वैकल्पिक जानकारी",
    comingSoon: "चाँडै आउँदैछ",
    loading: "लोड हुँदै...",
    quickActions: "छिटो कार्य",
    faqs: "प्रश्नोत्तर",
    resources: "स्रोतहरू",
    emailSupport: "इमेल समर्थन",
    callUs: "हामीलाई कल गर्नुहोस्",
    contact: "सम्पर्क",
    shareApp: "एप साझा गर्नुहोस्",
    shareAppMessage: "elearn Nep हेर्नुहोस्! https://www.elearn.com",
    unableToShareNow: "अहिले साझा गर्न सकिएन।",
    faqResetPasswordQ: "पासवर्ड कसरी रिसेट गर्ने?",
    faqResetPasswordA: "सेटिङ्स > खाता सुरक्षा > पासवर्ड परिवर्तनमा जानुहोस्।",
    faqContactSupportQ: "समर्थनलाई कसरी सम्पर्क गर्ने?",
    faqContactSupportA: "सम्पर्क प्रयोग गरेर elearnnep@16gmail.com मा इमेल वा +977-9864158297 मा कल गर्नुहोस्।",
    faqPrivacyQ: "गोपनीयता नीति कहाँ पढ्न सक्छु?",
    faqPrivacyA: "सेटिङ्स > अबाउट > गोपनीयता नीतिमा जानुहोस् वा तलको लिंक थिच्नुहोस्।",
    faqDeleteAccountQ: "खाता कसरी मेटाउने?",
    faqDeleteAccountA: "सेटिङ्स > खाता सुरक्षा > खाता मेटाउन जानुहोस् र निर्देशनहरू पालना गर्नुहोस्।",
    // Generic errors
    error: "त्रुटि",
    unableToLoadDownloads: "डाउनलोडहरू लोड गर्न सकिएन",
    failedToShareFile: "फाइल सेयर गर्न असफल भयो",
    failedToDeleteFile: "फाइल मेटाउन असफल भयो",
    failedToDeleteSomeFiles: "केही फाइलहरू मेटाउन असफल भयो",
    failedToClearAll: "सबै फाइलहरू हटाउन असफल भयो",
    
    // Class Screen
    class: "कक्षा",
    searchBooksNotes: "पुस्तकहरू, नोटहरू खोज्नुहोस्...",
    textbooks: "पाठ्यपुस्तकहरू",
    guidebooks: "गाइडबुकहरू",
    previousPapers: "अघिल्लो पेपरहरू",
    practiceQuestions: "अभ्यास प्रश्नहरू",
    cdcApprovedBooks: "CDC अनुमोदित पुस्तकहरू अंग्रेजी र नेपालीमा",
    chapterWiseNotes: "अध्यायवार नोटहरू, व्याख्या र परीक्षा",
    lastYearsExams: "पछिल्लो ३-५ वर्षको बोर्ड/फाइनल परीक्षा पहुँच",
    expectedQuestions: "परीक्षाका लागि अपेक्षित प्रश्नहरू: छोटो, लामो",
    recentActivity: "हालैका गतिविधिहरू",
    // Notifications
    notifications: "सूचनाहरू",
    clearAll: "सबै हटाउनुहोस्",
    noNotificationsYet: "अहिलेसम्म कुनै सूचना छैन",
    markAsRead: "पढिएको रूपमा चिन्हित गर्नुहोस्",
    markAsUnread: "नपढिएको रूपमा चिन्हित गर्नुहोस्",
    markAllAsRead: "सबैलाई पढिएको बनाउनुहोस्",
    markAllAsUnread: "सबैलाई नपढिएको बनाउनुहोस्",
    // Downloads toolbar/actions
    select: "छान्नुहोस्",
    selectAll: "सबै छान्नुहोस्",
    clear: "खाली",
    delete: "मेटाउनुहोस्",
    done: "भयो",
    noDownloadsYet: "अहिलेसम्म कुनै डाउनलोड छैन",
    downloadsAppearHere: "तपाईंका डाउनलोड गरिएका फाइलहरू यहाँ देखिन्छन्।",
    cancel: "रद्द",
    clearAllConfirmTitle: "सबै हटाउनुहोस्",
    clearAllConfirmMsg: "सबै डाउनलोड गरिएका फाइलहरू मेटाउने?",
    deleteSelectedConfirmTitle: "मेटाउनुहोस्",
    deleteSelectedConfirmMsg: "छानिएका फाइलहरू मेटाउने?",
    selected: "छानिएको",
    sharingNotAvailable: "यो उपकरणमा सेयरिङ उपलब्ध छैन",
    // Privacy Policy
    privacyUpdated: "अन्तिम अद्यावधिक: जनवरी २०२४",
    privacyIntro: "EduNepal मा, हामी तपाईंको गोपनीयता सुरक्षित गर्न र तपाईंको व्यक्तिगत जानकारीको सुरक्षा सुनिश्चित गर्न प्रतिबद्ध छौं। यो गोपनीयता नीतिले हामीले तपाईंको डाटा कसरी सङ्कलन, प्रयोग र सुरक्षित गर्छौं भनेर व्याख्या गर्छ।",
    privacyInfoWeCollectTitle: "हामीले के जानकारी सङ्कलन गर्छौं",
    privacyInfoWeCollectContent: "हामी तपाईंले प्रत्यक्ष रूपमा उपलब्ध गराउनु भएको जानकारी सङ्कलन गर्छौं, जस्तै तपाईंले खाता सिर्जना गर्दा, हाम्रा सेवा प्रयोग गर्दा, वा सपोर्टका लागि हामीलाई सम्पर्क गर्दा।",
    privacyHowWeUseTitle: "हामी तपाईंको जानकारी कसरी प्रयोग गर्छौं",
    privacyHowWeUseContent: "हामीले सङ्कलन गरेको जानकारी सेवाहरू उपलब्ध गराउन, कायम राख्न, सुधार गर्न, कारोबार प्रक्रिया गर्न, र तपाईंसँग सञ्चार गर्न प्रयोग गर्छौं।",
    privacySharingTitle: "जानकारी सेयरिङ",
    privacySharingContent: "यस नीतिमा वर्णन गरिएअनुसार बाहेक, तपाईंको सहमति बिना हामी तपाईंको व्यक्तिगत जानकारी तेस्रो पक्षसँग बेच्दैनौं, साटासाट गर्दैनौं वा हस्तान्तरण गर्दैनौं।",
    privacySecurityTitle: "डाटा सुरक्षा",
    privacySecurityContent: "हामी अनधिकृत पहुँच, परिवर्तन, प्रकटीकरण वा नष्टिकरणबाट तपाईंको व्यक्तिगत जानकारीलाई जोगाउन उपयुक्त सुरक्षा उपायहरू लागू गर्छौं।",
    privacyYourRightsTitle: "तपाईंका अधिकार",
    privacyYourRightsContent: "तपाईं आफ्नो व्यक्तिगत जानकारी पहुँच, अपडेट वा मेटाउन सक्नुहुन्छ। तपाईं केही सञ्चारबाट बाहिर निस्कन (opt out) पनि सक्नुहुन्छ।",
    privacyChangesTitle: "यस नीतिमा परिवर्तन",
    privacyChangesContent: "हामी समय-समयमा यस गोपनीयता नीतिमा परिवर्तन गर्न सक्छौं। हामी यो पृष्ठमा नयाँ नीति पोस्ट गरेर परिवर्तनको जानकारी दिनेछौं।",
    privacyContactFooter: "यस गोपनीयता नीतिबारे कुनै प्रश्न भएमा, कृपया privacy@edunepal.com मा सम्पर्क गर्नुहोस्",
    privacyPolicySubtitle: "हामीले डाटा कसरी सङ्कलन र प्रयोग गर्छौं",
    termsConditionsSubtitle: "तपाईंका अधिकार र जिम्मेवारी",
    // Notification Settings screen
    notificationSettingsTitle: "सूचना सेटिङ्स",
    notificationSettingsSubtitle: "तपाईं सूचनाहरू र अपडेट कसरी प्राप्त गर्नुहुन्छ प्रबन्ध गर्नुहोस्",
    pushNotifications: "पुष सूचनाहरू",
    pushNotificationsDesc: "रियल-टाइम अपडेटका लागि पुष सूचनाहरू सक्षम गर्नुहोस्",
    studyReminders: "अध्ययन सम्झाउने",
    studyRemindersDesc: "तपाईंको अध्ययन तालिका र लक्ष्यबारे सम्झना पाउनुहोस्",
    newContentAvailable: "नयाँ सामाग्री उपलब्ध",
    newContentAvailableDesc: "नयाँ अध्ययन सामग्री थपिँदा सूचनाहरू",
    emailNotificationsSection: "इमेल सूचनाहरू",
    emailNotifications: "इमेल सूचनाहरू",
    emailNotificationsDesc: "महत्वपूर्ण अपडेट र घोषणा इमेलमार्फत",
    weeklyDigest: "साप्ताहिक सार",
    weeklyDigestDesc: "तपाईंको प्रगति र नयाँ सामग्रीको साप्ताहिक सार",
    marketingEmails: "मार्केटिङ इमेल",
    marketingEmailsDesc: "प्रमोशनल अफर र शैक्षिक सुझावहरू",
    systemSecuritySection: "प्रणाली र सुरक्षा",
    systemSecuritySectionDesc: "महत्वपूर्ण प्रणाली र सुरक्षा सूचनाहरू",
    smsAlerts: "एसएमएस अलर्ट",
    smsAlertsDesc: "महत्वपूर्ण सुरक्षा अलर्टहरू एसएमएसमार्फत",
    systemUpdates: "प्रणाली अद्यावधिक",
    systemUpdatesDesc: "एप अपडेट र मर्मतसम्भार सूचनाहरू",
    infoChangeAnytime: "यी सेटिङहरू तपाईंले जेकुनै बेला परिवर्तन गर्न सक्नुहुन्छ। केही सूचनाहरू सुरक्षा कारण आवश्यक हुन सक्छन्।",
    saveNotificationSettings: "सूचना सेटिङ्स बचत गर्नुहोस्",
    saving: "बचत हुँदै...",
    success: "सफलता",
    notifSettingsSaved: "सूचना सेटिङहरू सफलतापूर्वक बचत गरियो!",
    failedToSaveSettings: "सेटिङहरू बचत गर्न असफल भयो। कृपया फेरि प्रयास गर्नुहोस्।",
    // Terms & Conditions
    termsUpdated: "अन्तिम अद्यावधिक: जनवरी २०२४",
    termsIntro: "कृपया elearn Nep प्रयोग गर्नु अघि यी नियम र सर्तहरू ध्यानपूर्वक पढ्नुहोस्। यी सर्तहरूले हाम्रो शैक्षिक प्लेटफर्म र सेवाहरूको तपाईंको प्रयोगलाई निर्देशित गर्छन्।",
    termsAcceptanceTitle: "नियमहरूको स्वीकृति",
    termsAcceptanceContent: "elearn Nep प्रयोग गरेर, तपाईं यस सम्झौताका नियम र प्रावधानहरू पालना गर्न सहमत हुनुहुन्छ।",
    termsUseLicenseTitle: "प्रयोग लाइसेन्स",
    termsUseLicenseContent: "elearn Nep लाई व्यक्तिगत, गैर-व्यावसायिक तात्कालिक हेर्नका लागि अस्थायी रूपमा पहुँच अनुमति दिइएको छ।",
    termsUserAccountTitle: "प्रयोगकर्ता खाता",
    termsUserAccountContent: "तपाईं आफ्नो खाता प्रमाणहरू सुरक्षित राख्न र आफ्नो खातामा हुने सबै गतिविधिहरूको लागि जिम्मेवार हुनुहुन्छ।",
    termsProhibitedUsesTitle: "प्रतिबन्धित प्रयोग",
    termsProhibitedUsesContent: "तपाईं हाम्रो सेवालाई कुनै गैरकानुनी वा अनधिकृत उद्देश्यका लागि प्रयोग गर्न सक्नुहुन्न, वा आफ्नो क्षेत्राधिकारका कुनै पनि कानूनहरू उल्लङ्घन गर्न सक्नुहुन्न।",
    termsContentTitle: "सामग्री",
    termsContentContent: "हाम्रो सेवाले शैक्षिक सामग्री पहुँच गर्न अनुमति दिन्छ। तपाईं सामग्रीको प्रयोगको लागि जिम्मेवार हुनुहुन्छ र बौद्धिक सम्पत्ति अधिकारको सम्मान गर्नुपर्छ।",
    termsPrivacyPolicyTitle: "गोपनीयता नीति",
    termsPrivacyPolicyContent: "तपाईंको गोपनीयता हामीलाई महत्त्वपूर्ण छ। कृपया हाम्रो गोपनीयता नीति समीक्षा गर्नुहोस्, जसले सेवाको तपाईंको प्रयोगलाई पनि निर्देशित गर्छ।",
    termsTerminationTitle: "समाप्ति",
    termsTerminationContent: "हामी यी नियमहरूको उल्लङ्घन भएको विश्वास हुने व्यवहारका लागि पूर्वसूचना बिना नै तपाईंको खाता र सेवामा पहुँच तुरुन्त निलम्बन वा समाप्त गर्न सक्छौं।",
    termsChangesTitle: "नियमहरूमा परिवर्तन",
    termsChangesContent: "हामी कुनै पनि समयमा यी नियमहरू परिमार्जन गर्ने अधिकार राख्छौं। कुनै महत्वपूर्ण परिवर्तनबारे प्रयोगकर्तालाई सूचित गरिनेछ।",
    termsQuestionsFooter: "यी नियम र सर्तहरूबारे कुनै प्रश्न भएमा, कृपया elearnnep@16gmail.com मा सम्पर्क गर्नुहोस्",
    termsPlaceholder: "नियम र सर्तहरूको पूर्ण पाठ यहाँ जान्छ। यस सामग्रीले elearn Nep एप र सेवाहरू कसरी प्रयोग गर्न सकिन्छ, तपाईंको जिम्मेवारीहरू, र हाम्रा नीतिहरू वर्णन गर्दछ।"
  },
  
  hi: {
    // Textbook Component
    class10Textbooks: "कक्षा 10 की पाठ्यपुस्तकें",
    chooseMediumAndSubject: "अपना माध्यम और विषय चुनें",
    englishMedium: "अंग्रेजी माध्यम",
    nepaliMedium: "नेपाली माध्यम",
    subjects: "विषय",
    english: "अंग्रेजी",
    mathematics: "गणित",
    science: "विज्ञान",
    socialStudies: "सामाजिक अध्ययन",
    computerScience: "कंप्यूटर विज्ञान",
    optionalMath: "वैकल्पिक गणित",
    
    // Authentication
    welcomeBack: "वापस स्वागत है",
    createAccount: "खाता बनाएं",
    joinEduNepal: "आज elearn Nep से जुड़ें",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    error: "त्रुटि",
    // Drawer descriptions
    drawerDescHome: "मुख्य डैशबोर्ड पर जाएँ",
    drawerDescProfile: "अपनी प्रोफ़ाइल जानकारी देखें",
    drawerDescSettings: "एप की प्राथमिकताएँ प्रबंधित करें",
    drawerDescLanguage: "एप की भाषा बदलें",
    drawerDescDownloads: "अपनी डाउनलोड की गई सामग्री देखें",
    drawerDescTheme: "लाइट/डार्क मोड स्विच करें",
    drawerDescHelpSupport: "उत्तर खोजें या सपोर्ट से संपर्क करें",
    drawerDescTerms: "नियम और नीतियाँ पढ़ें",
    drawerDescContactUs: "प्रश्नों के लिए हमसे संपर्क करें",
    
    // एडमिन डैशबोर्ड
    adminAccessDenied: "प्रवेश अस्वीकृत। केवल व्यवस्थापकों के लिए।",
    adminDashboardTitle: "एडमिन डैशबोर्ड",
    adminWelcomeBack: "वापसी पर स्वागत,",
    systemOverview: "सिस्टम अवलोकन",
    totalUsers: "कुल उपयोगकर्ता",
    activeUsers: "सक्रिय उपयोगकर्ता",
    onlineUsers: "ऑनलाइन उपयोगकर्ता",
    contentItems: "कंटेंट आइटम",
    booksNotesPapers: "पुस्तकें, नोट्स, पेपर",
    systemHealth: "सिस्टम स्वास्थ्य",
    last24Hours: "पिछले 24 घंटे",
    live: "लाइव",
    userManagement: "यूज़र मैनेजमेंट",
    userManagementDesc: "छात्र खातों और अनुमतियों का प्रबंधन करें",
    contentManagement: "कंटेंट मैनेजमेंट",
    contentManagementDesc: "शैक्षणिक सामग्री अपलोड और व्यवस्थित करें",
    systemAnalytics: "सिस्टम एनालिटिक्स",
    systemAnalyticsDesc: "विस्तृत उपयोग आँकड़े और रिपोर्ट देखें",
    notificationCenter: "सूचना केंद्र",
    notificationCenterDesc: "सभी उपयोगकर्ताओं को घोषणाएँ भेजें",
    systemSettings: "सिस्टम सेटिंग्स",
    systemSettingsDesc: "एप-स्तरीय सेटिंग्स और प्राथमिकताएँ कॉन्फ़िगर करें",
    backupSecurity: "बैकअप और सुरक्षा",
    backupSecurityDesc: "डेटा बैकअप और सुरक्षा सेटिंग्स प्रबंधित करें",
    systemStatus: "सिस्टम स्थिति",
    serverStatus: "सर्वर स्थिति",
    database: "डेटाबेस",
    connected: "कनेक्टेड",
    disconnected: "डिसकनेक्टेड",
    storageUsed: "उपयोग किया गया भंडारण",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    // Settings (index)
    settingsSearchPlaceholder: "सेटिंग्स खोजें...",
    settingsSearchResults: "खोज परिणाम",
    settingsNoMatches: "कोई मिलान नहीं मिला",
    settingsAdminControls: "प्रशासक नियंत्रण",
    settingsAccountSecurity: "खाता सुरक्षा",
    settingsPrivacyData: "गोपनीयता और डेटा",
    settingsNotifications: "सूचनाएँ",
    settingsPreferences: "वरीयताएँ",
    settingsHelpSupport: "मदद और समर्थन",
    settingsAbout: "के बारे में",
    settingsAccountActions: "खाता कार्य",
    adminDashboard: "एडमिन डैशबोर्ड",
    adminDashboardDesc: "उपयोगकर्ता, सामग्री और सिस्टम प्रबंधित करें",
    changePassword: "पासवर्ड बदलें",
    changePasswordDesc: "अपने खाते की सुरक्षा सेटिंग्स अपडेट करें",
    updateEmail: "ईमेल पता अपडेट करें",
    updateEmailDesc: "अपना ईमेल बदलें",
    deleteAccount: "खाता हटाएँ",
    deleteAccountDesc: "अपने खाते को स्थायी रूप से हटाएँ",
    privacyDashboard: "गोपनीयता डैशबोर्ड",
    notificationSettings: "सूचना सेटिंग्स",
    notificationSettingsDesc: "सभी सूचना प्राथमिकताओं का प्रबंधन करें",
    choosePreferredLanguage: "अपनी पसंदीदा भाषा चुनें",
    languageChangeAppliedImmediately: "भाषा परिवर्तन तुरंत पूरे ऐप में लागू हो जाएगा।",
    contentRegion: "सामग्री क्षेत्र",
    contentRegionValueNepal: "नेपाल",
    themeSettings: "थीम सेटिंग्स",
    themeSettingsDesc: "लाइट, डार्क या ऑटो",
    userGuides: "उपयोगकर्ता गाइड",
    applicationVersion: "एप्लिकेशन संस्करण",
    roleAdministrator: "प्रशासक",
    roleStudent: "विद्यार्थी",
    userFallback: "उपयोगकर्ता",
    // Admin
    admin: "एडमिन",
    adminNotificationCenter: "नोटिफिकेशन सेंटर",
    adminNotificationCenterDesc: "इतिहास देखें और सूचनाओं का प्रबंधन करें",
    adminLogin: "एडमिन लॉगिन",
    userLogin: "यूजर लॉगिन",
    demoCredentials: "डेमो क्रेडेंशियल्स",
    email: "ईमेल",
    password: "पासवर्ड",
    username: "यूजरनेम",
    fullName: "पूरा नाम",
    phoneNumber: "फोन नंबर",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    alreadyHaveAccount: "पहले से खाता है? लॉगिन करें",
    
    // Profile
    profile: "प्रोफाइल",
    personalInformation: "व्यक्तिगत जानकारी",
    accountDetails: "खाता विवरण",
    emailAddress: "ईमेल पता",
    accountRole: "खाता भूमिका",
    memberSince: "सदस्य बने",
    location: "स्थान",
    editProfile: "प्रोफाइल संपादित करें",
    loadingProfile: "प्रोफाइल लोड हो रहा है...",
    welcomeToEduNepal: "elearn Nep में आपका स्वागत है",
    classes: "कक्षाएं",
    class: "कक्षा",
    years: "साल",
    active: "सक्रिय",
    // Class subtitles
    classSubtitle1: "कम उम्र के छात्रों के लिए बुनियादी अध्ययन",
    classSubtitle2: "रोचक पाठ और गतिविधियों के साथ",
    classSubtitle3: "मध्यम स्तर का केंद्रित अध्ययन",
    classSubtitle4: "उन्नत विषय और अनुप्रयोग",
    classSubtitle5: "सभी के लिए व्यापक पाठ्यक्रम",
    classSubtitle6: "विज्ञान, गणित आदि में गहराई से अध्ययन",
    classSubtitle7: "पूर्व-माध्यमिक बुनियादी सामग्री",
    classSubtitle8: "माध्यमिक शिक्षा की बुनियाद",
    classSubtitle9: "उन्नत माध्यमिक विषय",
    classSubtitle10: "SEE परीक्षा की तैयारी",
    classSubtitle11: "उच्च माध्यमिक की नींव",
    classSubtitle12: "विश्वविद्यालय की ओर पुल",
    
    // Navigation
    home: "होम",
    settings: "सेटिंग्स",
    language: "भाषा",
    downloads: "डाउनलोड",
    theme: "थीम",
    helpSupport: "मदद और समर्थन",
    helpSupportSubtitle: "उत्तर खोजें, हमसे संपर्क करें, और उपयोगी संसाधन देखें",
    termsConditions: "नियम और शर्तें",
    contactUs: "संपर्क करें",
    contactSubtitle: "हमारी सपोर्ट टीम से संपर्क करें",
    aboutApp: "ऐप के बारे में",
    privacyPolicy: "गोपनीयता नीति",
    userGuides: "यूज़र गाइड्स",
    accountSecurity: "खाता सुरक्षा",
    adminDashboard: "एडमिन डैशबोर्ड",
    systemNotifications: "सिस्टम सूचनाएँ",
    systemLogs: "सिस्टम लॉग्स",
    developerTools: "डेवलपर टूल्स",
    notificationSettings: "सूचना सेटिंग्स",
    languageRegion: "भाषा और क्षेत्र",
    regionSettings: "क्षेत्र सेटिंग्स",
    privacySettings: "गोपनीयता सेटिंग्स",
    updatePassword: "पासवर्ड अपडेट",
    updateEmail: "ईमेल अपडेट",
    deleteAccount: "खाता हटाएँ",
    
    // General
    general: "सामान्य",
    supportAccount: "समर्थन और खाता",
    eduNepal: "elearn Nep",
    optional: "वैकल्पिक",
    required: "आवश्यक जानकारी",
    optionalInformation: "वैकल्पिक जानकारी",
    comingSoon: "जल्द आ रहा है",
    loading: "लोड हो रहा है...",
    quickActions: "त्वरित क्रियाएँ",
    faqs: "सामान्य प्रश्न",
    resources: "संसाधन",
    emailSupport: "ईमेल समर्थन",
    callUs: "हमें कॉल करें",
    contact: "संपर्क",
    shareApp: "ऐप साझा करें",
    shareAppMessage: "elearn Nep देखें! https://www.elearn.com",
    unableToShareNow: "अभी साझा नहीं कर सकते।",
    faqResetPasswordQ: "मैं अपना पासवर्ड कैसे रीसेट करूं?",
    faqResetPasswordA: "पासवर्ड रीसेट करने के लिए सेटिंग्स > खाता सुरक्षा > पासवर्ड बदलें पर जाएँ।",
    faqContactSupportQ: "मैं समर्थन से कैसे संपर्क कर सकता/सकती हूँ?",
    faqContactSupportA: "संपर्क का उपयोग करके elearnnep@16gmail.com पर ईमेल करें या +977-9864158297 पर कॉल करें।",
    faqPrivacyQ: "मैं गोपनीयता नीति कहाँ पढ़ सकता/सकती हूँ?",
    faqPrivacyA: "सेटिंग्स > अबाउट > गोपनीयता नीति पर जाएँ या नीचे दिए लिंक पर टैप करें।",
    faqDeleteAccountQ: "मैं अपना खाता कैसे हटाऊं?",
    faqDeleteAccountA: "सेटिंग्स > खाता सुरक्षा > खाता हटाएँ पर जाएँ और चरणों का पालन करें।",
    // Generic errors
    error: "त्रुटि",
    unableToLoadDownloads: "डाउनलोड लोड नहीं हो सके",
    failedToShareFile: "फ़ाइल साझा करने में विफल",
    failedToDeleteFile: "फ़ाइल हटाने में विफल",
    failedToDeleteSomeFiles: "कुछ फ़ाइलें हटाने में विफल",
    failedToClearAll: "सभी फ़ाइलें हटाने में विफल",
    
    // Class Screen
    class: "कक्षा",
    searchBooksNotes: "किताबें, नोट्स खोजें...",
    textbooks: "पाठ्यपुस्तकें",
    guidebooks: "गाइडबुक्स",
    previousPapers: "पिछले पेपर्स",
    practiceQuestions: "अभ्यास प्रश्न",
    cdcApprovedBooks: "CDC अनुमोदित पुस्तकें अंग्रेजी और नेपाली में",
    chapterWiseNotes: "अध्यायवार नोट्स, व्याख्या और परीक्षा",
    lastYearsExams: "पिछले 3-5 साल के बोर्ड/फाइनल परीक्षा एक्सेस",
    expectedQuestions: "परीक्षा के लिए अपेक्षित प्रश्न: छोटे, लंबे",
    recentActivity: "हाल की गतिविधि",
    // Notifications
    notifications: "सूचनाएँ",
    clearAll: "सभी हटाएँ",
    noNotificationsYet: "अभी कोई सूचना नहीं",
    markAsRead: "पढ़ा हुआ करें",
    markAsUnread: "अपठित करें",
    markAllAsRead: "सभी को पढ़ा हुआ करें",
    markAllAsUnread: "सभी को अपठित करें",
    // Downloads toolbar/actions
    select: "चुनें",
    selectAll: "सभी चुनें",
    clear: "साफ़",
    delete: "हटाएँ",
    done: "हो गया",
    noDownloadsYet: "अभी कोई डाउनलोड नहीं",
    downloadsAppearHere: "आपकी डाउनलोड की गई फाइलें यहाँ दिखेंगी।",
    cancel: "रद्द",
    clearAllConfirmTitle: "सभी हटाएँ",
    clearAllConfirmMsg: "सभी डाउनलोड फाइलें हटाएँ?",
    deleteSelectedConfirmTitle: "हटाएँ",
    deleteSelectedConfirmMsg: "चयनित फाइलें हटाएँ?",
    selected: "चुना हुआ",
    sharingNotAvailable: "इस डिवाइस पर शेयरिंग उपलब्ध नहीं है",
    // Privacy Policy
    privacyUpdated: "अंतिम अपडेट: जनवरी 2024",
    privacyIntro: "EduNepal में, हम आपकी गोपनीयता की रक्षा करने और आपकी व्यक्तिगत जानकारी की सुरक्षा सुनिश्चित करने के लिए प्रतिबद्ध हैं। यह गोपनीयता नीति बताती है कि हम आपका डेटा कैसे एकत्रित, उपयोग और सुरक्षित करते हैं।",
    privacyInfoWeCollectTitle: "हम कौन सी जानकारी एकत्रित करते हैं",
    privacyInfoWeCollectContent: "हम वह जानकारी एकत्रित करते हैं जो आप सीधे हमें प्रदान करते हैं, जैसे कि जब आप खाता बनाते हैं, हमारी सेवाओं का उपयोग करते हैं, या सहायता के लिए हमसे संपर्क करते हैं।",
    privacyHowWeUseTitle: "हम आपकी जानकारी का उपयोग कैसे करते हैं",
    privacyHowWeUseContent: "हम एकत्रित जानकारी का उपयोग हमारी सेवाएँ प्रदान करने, बनाए रखने और सुधारने, लेनदेन को संसाधित करने, और आपसे संवाद करने के लिए करते हैं।",
    privacySharingTitle: "जानकारी साझा करना",
    privacySharingContent: "इस नीति में वर्णित के अलावा, आपकी सहमति के बिना हम आपकी व्यक्तिगत जानकारी को तीसरे पक्षों को नहीं बेचते, न व्यापार करते हैं और न ही स्थानांतरित करते हैं।",
    privacySecurityTitle: "डेटा सुरक्षा",
    privacySecurityContent: "हम आपकी व्यक्तिगत जानकारी को अनधिकृत पहुँच, परिवर्तन, प्रकटीकरण, या नष्ट होने से बचाने के लिए उपयुक्त सुरक्षा उपाय लागू करते हैं।",
    privacyYourRightsTitle: "आपके अधिकार",
    privacyYourRightsContent: "आप अपनी व्यक्तिगत जानकारी तक पहुँच, उसे अपडेट या हटाने का अधिकार रखते हैं। आप हमारी कुछ संचार सेवाओं से बाहर निकलने (opt out) का विकल्प भी चुन सकते हैं।",
    privacyChangesTitle: "इस नीति में परिवर्तन",
    privacyChangesContent: "हम समय-समय पर इस गोपनीयता नीति को अपडेट कर सकते हैं। हम इस पृष्ठ पर नई नीति पोस्ट करके किसी भी बदलाव की सूचना देंगे।",
    privacyContactFooter: "यदि आपके पास इस गोपनीयता नीति के बारे में कोई प्रश्न हैं, तो कृपया privacy@edunepal.com पर हमसे संपर्क करें",
    privacyPolicySubtitle: "हम डेटा कैसे एकत्र और उपयोग करते हैं",
    termsConditionsSubtitle: "आपके अधिकार और जिम्मेदारियाँ",
    // Notification Settings screen
    notificationSettingsTitle: "सूचना सेटिंग्स",
    notificationSettingsSubtitle: "आप सूचनाएँ और अपडेट कैसे प्राप्त करते हैं, प्रबंधित करें",
    pushNotifications: "पुश सूचनाएँ",
    pushNotificationsDesc: "रियल-टाइम अपडेट के लिए पुश सूचनाएँ सक्षम करें",
    studyReminders: "अध्ययन रिमाइंडर",
    studyRemindersDesc: "अपने अध्ययन शेड्यूल और लक्ष्यों के बारे में याद दिलाएं",
    newContentAvailable: "नया कंटेंट उपलब्ध",
    newContentAvailableDesc: "जब नया अध्ययन सामग्री जोड़ा जाए तो सूचनाएँ",
    emailNotificationsSection: "ईमेल सूचनाएँ",
    emailNotifications: "ईमेल सूचनाएँ",
    emailNotificationsDesc: "ईमेल के माध्यम से महत्वपूर्ण अपडेट और घोषणाएँ",
    weeklyDigest: "साप्ताहिक डाइजेस्ट",
    weeklyDigestDesc: "आपकी प्रगति और नए कंटेंट का साप्ताहिक सारांश",
    marketingEmails: "मार्केटिंग ईमेल",
    marketingEmailsDesc: "प्रचार ऑफ़र और शैक्षिक सुझाव",
    systemSecuritySection: "सिस्टम और सुरक्षा",
    systemSecuritySectionDesc: "महत्वपूर्ण सिस्टम और सुरक्षा सूचनाएँ",
    smsAlerts: "एसएमएस अलर्ट",
    smsAlertsDesc: "महत्वपूर्ण सुरक्षा अलर्ट एसएमएस द्वारा",
    systemUpdates: "सिस्टम अपडेट",
    systemUpdatesDesc: "ऐप अपडेट और रखरखाव सूचनाएँ",
    infoChangeAnytime: "आप इन सेटिंग्स को कभी भी बदल सकते हैं। कुछ सूचनाएँ सुरक्षा उद्देश्यों के लिए आवश्यक हो सकती हैं।",
    saveNotificationSettings: "सूचना सेटिंग्स सहेजें",
    saving: "सहेजा जा रहा है...",
    success: "सफलता",
    notifSettingsSaved: "सूचना सेटिंग्स सफलतापूर्वक सहेजी गई!",
    failedToSaveSettings: "सेटिंग्स सहेजने में विफल। कृपया पुनः प्रयास करें।",
    // Terms & Conditions
    termsUpdated: "अंतिम अपडेट: जनवरी 2024",
    termsIntro: "कृपया elearn Nep का उपयोग करने से पहले इन नियम और शर्तों को ध्यान से पढ़ें। ये शर्तें हमारे शैक्षणिक प्लेटफ़ॉर्म और सेवाओं के आपके उपयोग को नियंत्रित करती हैं।",
    termsAcceptanceTitle: "नियमों की स्वीकृति",
    termsAcceptanceContent: "elearn Nep का उपयोग करके, आप इस अनुबंध की शर्तों और प्रावधानों का पालन करने के लिए सहमत होते हैं।",
    termsUseLicenseTitle: "उपयोग लाइसेंस",
    termsUseLicenseContent: "elearn Nep तक अस्थायी रूप से व्यक्तिगत, गैर-व्यावसायिक अस्थाई देखने के लिए पहुँच की अनुमति दी जाती है।",
    termsUserAccountTitle: "यूजर खाता",
    termsUserAccountContent: "आप अपने खाते के क्रेडेंशियल्स की सुरक्षा और अपने खाते के अंतर्गत होने वाली सभी गतिविधियों के लिए जिम्मेदार हैं।",
    termsProhibitedUsesTitle: "प्रतिबंधित उपयोग",
    termsProhibitedUsesContent: "आप हमारी सेवा का उपयोग किसी भी गैरकानूनी या अनधिकृत उद्देश्य के लिए नहीं कर सकते, या अपने क्षेत्राधिकार के किसी भी कानून का उल्लंघन नहीं कर सकते।",
    termsContentTitle: "सामग्री",
    termsContentContent: "हमारी सेवा आपको शैक्षणिक सामग्री तक पहुँच प्रदान करती है। आपको सामग्री के उपयोग के लिए जिम्मेदार होना चाहिए और बौद्धिक संपदा अधिकारों का सम्मान करना चाहिए।",
    termsPrivacyPolicyTitle: "गोपनीयता नीति",
    termsPrivacyPolicyContent: "आपकी गोपनीयता हमारे लिए महत्वपूर्ण है। कृपया हमारी गोपनीयता नीति की समीक्षा करें, जो आपकी सेवा के उपयोग को भी नियंत्रित करती है।",
    termsTerminationTitle: "समापन",
    termsTerminationContent: "हम इन नियमों का उल्लंघन करने वाले आचरण के लिए बिना किसी पूर्व सूचना के, तुरंत आपके खाते और सेवा तक पहुँच को निलंबित या समाप्त कर सकते हैं।",
    termsChangesTitle: "नियमों में परिवर्तन",
    termsChangesContent: "हम किसी भी समय इन शर्तों में संशोधन करने का अधिकार रखते हैं। किसी भी महत्वपूर्ण परिवर्तन के बारे में उपयोगकर्ताओं को सूचित किया जाएगा।",
    termsQuestionsFooter: "यदि आपको इन नियम और शर्तों के बारे में कोई प्रश्न हैं, तो कृपया हमसे elearnnep@16gmail.com पर संपर्क करें",
    termsPlaceholder: "नियम और शर्तों का पूर्ण पाठ यहाँ होगा। यह सामग्री बताती है कि आप elearn Nep एप और सेवाओं का उपयोग कैसे कर सकते हैं, आपकी जिम्मेदारियाँ, और हमारी नीतियाँ।"
  }
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // Default English

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const storedLang = await AsyncStorage.getItem('appLanguage');
        if (storedLang && translations[storedLang]) {
          setLanguage(storedLang);
        }
      } catch (error) {
        console.log('Error loading language:', error);
      }
    };
    loadLanguage();
  }, []);

  const changeLanguage = async (langCode) => {
    if (translations[langCode]) {
      setLanguage(langCode);
      try {
        await AsyncStorage.setItem('appLanguage', langCode);
      } catch (error) {
        console.log('Error saving language:', error);
      }
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const getAvailableLanguages = () => [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' }
  ];

  return (
    <LanguageContext.Provider value={{ 
      language, 
      changeLanguage, 
      t, 
      getAvailableLanguages 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
